development:
  clients:
    default:
      database: raceday_development
      hosts:
        - mongo:27017
      options:
        user: 'root'
        password: 'example'
        ssl: true
        ssl_verify: true
        # The file containing a set of concatenated certification authority certifications
        # used to validate certs passed from the other end of the connection.
        ssl_ca_cert: rootCA_workstation.key

test:
      clients:
        default:
          database: raceday_test
          hosts:
            - mongo:27017
        options:
          user: 'root'
          password: 'example'




